apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqttprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqttprocessing
  template:
    metadata:
      labels:
        app: mqttprocessing
    spec:
      containers:
      - name: mqttprocessing
        image: wernes1/mqttprocessing:2b1719c040ac9d3f84474a8558670aaf5bfaf8d7