apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqttprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqttprocessing
  template:
    metadata:
      labels:
        app: mqttprocessing
    spec:
      containers:
      - name: mqttprocessing
        image: wernes1/mqttprocessing:27664236ca83dc8ad251a50acde9d8fbfd0f5330