apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqttprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqttprocessing
  template:
    metadata:
      labels:
        app: mqttprocessing
    spec:
      containers:
      - name: mqttprocessing
        image: wernes1/mqttprocessing:1c87a96ab442ecac14aff50f65caf00e57635ed0